---
name: Test-HTML-W3C
version: 0.04
author:
  - Victor E<lt>victor73@gmail.com<gt>
abstract: Perform W3C HTML validation testing
license: perl
requires:
  WebService::Validator::HTML::W3C: 0
  Test::Builder::Module: 0
build_requires:
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::More: 0
provides:
  Test::HTML::W3C:
    file: lib/Test/HTML/W3C.pm
    version: 0.04
generated_by: manually
